[package]
name = "study_helper"
version = "0.1.0"
edition = "2024"

# Dependencies
[dependencies]
eframe = "0.32.3"  # Replace with the latest version if needed
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"