[package]
name = "study_helper"
version = "0.1.0"
edition = "2024"

# Dependencies
[dependencies]
eframe = "0.32.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
sanitize-filename = "0.6.0"
rfd = "0.15.4"
log = "0.4"
env_logger = "0.11"